name: Build
on:
  push:
    branches:
      - main
    tags:
      - "v*"
jobs:
  build_and_publish:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [
            # ubuntu-latest,
            # macos-latest,
            windows-latest,
          ]
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: 14
      - name: Install VSBuild Tools
        run: npm install --global windows-build-tools
      - name: Install dependencies
        run: npm i
      - name: Verify dependencies
        run: npm ci
      - name: Build and Publish
        env:
          GITHUB_TOKEN: ${{ secrets.GH_TOKEN }}
        run: npm run publish
