name: Build
on:
  push:
    branches:
      - main
    tags:
      - "v*"

jobs:
  build_and_publish:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [
            # ubuntu-latest,
            # macos-latest,
            windows-latest,
          ]
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: 16.13.0
      - name: Install Visual Studio Build Tools
        uses: microsoft/setup-msbuild@v1.0.2
        with:
          vs-version: 16
      - name: Set VC ENV
        run: SET VCINSTALLDIR="C:\Program Files\Microsoft Visual Studio\2022\Enterprise\VC\"
      - name: Set MSB ENV
        run: SET msbuild_path="C:\Program Files\Microsoft Visual Studio\2022\Enterprise\VC\"
      - name: Set MSB npm
        run: npm config set msvs_version 2022
      - name: Install dependencies
        run: npm i
      - name: Verify dependencies
        run: npm ci
      - name: Build and Publish
        env:
          GITHUB_TOKEN: ${{ secrets.GH_TOKEN }}
        run: npm run publish
